language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
  - nosetests
deploy:
  provider: heroku
  api_key:
    secure: y1JigMGpP54fqlHr8fXZVPq5PVbKdefiAnKj4+EPwznVJDPf8Zcax4Nv53fHANrqf0HQqzueLWe1ot7uwQwsN3elepJttfNYzb09DQCGiGCsGxhxdROTctOXMg2iSAH8Rq3Bg6MF48miFpPIMwSWHccjRiEg+rcMYS+415lJoGacjImHPE/RHMlv+e1H6UtQFOPBBOw82A1q+4n4vJSOuCBgcO7izIFP32EJwO9QTVQg5RZl1UwQKk872AXtCt6UKGygRQ03/TLHd3dL4mPBxKRBa4Met9fr7ZXTzhiSoAl65+vpBGjw5z25Uj8L9KNswPy9at/HUYns0grZ2aHmQbgUChHIrwA9pQkJTxu/qy86phcX4KkHdt1TolSVvStcHCtgkyZB5a4lHkQPsrtXS6QRwtNw44+T+N+T30K/noQ6u2GNinCmACgVfMkIOzbKRPe9sWzERR0hfyGCyDHkoFC0KiecyaqyKwSFEDT1V6uC16pE5O6EPbCVk+P0Mw2vYS+8YVJuyg1icqJdoaJrcR2sDATHHGDircbvqgO3Zc+zHEAf3v19+c54lzaVI1m2BiElxfft8W2gVSjVvUu2ejCl8GcrhADtce5Iq0ikLnlSJlb013I1uHIEnorqA4lQNejzvX76a581vXex1/trxvcEimlwvTApDzdIIa5n5sQ=
  app: secure-lowlands-82682
  on:
    branch: master
    python: '3.4'
    repo: tomtom92/FlaskTaskr
